on: push

name: Go tests

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run test
      uses: cedrickring/golang-action@1.5.2
      run: go test